export const QUERY_KEY = {
  AUTH: {
    GET_ME: 'AUTH/GET_ME',
  },
  ADDRESS: {
    GET_ALL: 'ADDRESS/GET_ALL',
  },
  BRAND: {
    GET_ALL: 'BRAND/GET_ALL',
    GET_BY_ID: 'BRAND/GET_BY_ID',
    GET_BRANDIES_WITH_PRODUCTS: 'BRAND/GET_BRANDIES_WITH_PRODUCTS',
  },
  CATEGORY: {
    GET_ALL: 'CATEGORY/GET_ALL',
    GET_BY_ID: 'CATEGORY/GET_BY_ID',
    GET_WITH_PRODUCTS: 'CATEGORY/GET_WITH_PRODUCTS',
  },
  COUPON: {
    GET_ALL: 'COUPON/GET_ALL',
    GET_BY_ID: 'COUPON/GET_BY_ID',
    GET_TODAY: 'COUPON/GET_TODAY',
  },
  ORDER: {
    GET_ALL: 'ORDER/GET_ALL',
    GET_BY_ID: 'ORDER/GET_BY_ID',
    GET_ITEMS: 'ORDER/GET_ITEMS',
  },
  PAYMENT_ACCOUNT: {
    GET_ALL: 'PAYMENT_ACCOUNT/GET_ALL',
  },
  CARD: {
    GET_ALL: 'CARD/GET_ALL',
  },
  PRODUCT: {
    GET_ALL: 'PRODUCT/GET_ALL',
    GET_BY_ID: 'PRODUCT/GET_BY_ID',
    GET_FAVORITE: 'PRODUCT/GET_FAVORITE',
    GET_FEATURED: 'PRODUCT/GET_FEATURED',
    GET_RELATE: 'PRODUCT/GET_RELATE',
    GET_RECOMMEND: 'PRODUCT/GET_RECOMMEND',
    GET_BEST_SELLER: 'PRODUCT/GET_BEST_SELLER',
    GET_DISCOUNT: 'PRODUCT/GET_DISCOUNT',
    GET_POPULAR: 'PRODUCT/GET_POPULAR',
  },
  QUESTION: {
    GET_ALL: 'QUESTION/GET_ALL',
  },
  REVIEW: {
    GET_ALL: 'REVIEW/GET_ALL',
    GET_PRODUCT_REVIEW: 'REVIEW/GET_PRODUCT_REVIEW',
  },
  CHAT: {
    GET_ROOM: 'CHAT/GET_ROOM',
  },
};
